### ISSUE TITLE
Where to put Keystone Endpoint ?

### ISSUE THREAD

**Issue by EmilienM** [ging/horizon-js#1]
By default, be don't have to give credentials to connect, and we are in your infrastructure.

What is the way to configure our own Keystone Endpoint ?

**Comment by EmilienM** [comment]
I had a look at https://github.com/ging/horizon-js/blob/master/.gitignore
and we can see that you don't upload "/settings", is it normal ?

**Comment by jcague** [comment]
Hi Emilien, you can better take a look at: 

http://ging.github.com/jstack/

There is also a test page you can use for trying it:

http://ging.github.com/jstack/test/test.html

**Comment by EmilienM** [comment]
Thank you for quick reply.

**Comment by EmilienM** [comment]
I've read http://ging.github.com/jstack/test/test.html.

JStack is actually a Javascript API able to communicate with OpenStack, and if I understand Horizon-JS is using this API.

I need to know how can I configure Horizon-JS to be able to manage my OpenStack Environment.

Thank's for your help

**Comment by jcague** [comment]
At this time you can only configure your environment in: js/load-modules.js

Line 17: UTILS.Auth.initialize("http://mcu5.dit.upm.es:5000/v2.0/");

There you can put your own Keystone Endpoint URL

**Comment by EmilienM** [comment]
I actually did that at first, but it says that my credentials are wrong,
which are actually right.

Any idea ?

**Comment by jcague** [comment]
You can take a look at the log console. For example, if using Chrome you can press F12 and then click on Console.
